---
- name: "(CentOS) Add NGINX Repository"
  yum_repository:
    name: nginx
    description: Mainline CentOS NGINX Repository
    baseurl: http://nginx.org/packages/mainline/centos/{{ansible_distribution_major_version|int}}/$basearch/
    enabled: yes
    gpgcheck: no
  when: ansible_distribution == "CentOS"

- name: "(RedHat) Add NGINX Repository"
  yum_repository:
    name: nginx
    description: Mainline RedHat NGINX Repository
    baseurl: http://nginx.org/packages/mainline/rhel/{{ansible_distribution_major_version|int}}/$basearch/
    enabled: yes
    gpgcheck: no
  when: ansible_distribution == "RedHat"
